### PR TITLE
Apt dependency branch

### PR DESCRIPTION
**Pull request by rybectom**
Add a branch that is independent on local GLM (downloaded by travis) and supports only apt package. This resolves possible problems, e.g., when using the tinynurbs library as a git submodule.

### CODE REVIEW

**Comment by pradeep-pyro** [comment]
Hi @rybectom, could you explain what the problem was when using tinynurbs as a submodule? Did you want to use our own GLM library rather than the one that comes with tinynurbs?

**Comment by rybectom** [comment]
Hi @pradeep-pyro, thanks for the quick reply. Yes I want to use GLM installed from an apt package (specifically through rosdep, since I develop a ROS package). When I try to update the submodule (`git submodule update --init --recursive <path-to-tinynurbs>`), git gets confused by the dependencies folder (`No url found for submodule path '<path-to-tinynurbs>/tinynurbs/dependencies/glm' in .gitmodules`), although it should ignore it. I was able to solve this by the v0.1 tag which depends directly on the apt installation. I find it generally practical to be able to completely avoid travis and "submodule-submodules" and that's why I suggest this branch.

**Comment by rybectom** [comment]
@pradeep-pyro I probably found the cause of the problem. In order to have the empty directory dependencies/glm in your repository (which is normally not possible), you probably set it up as a submodule (should be indicated by the arrow on the glm folder [here](https://github.com/pradeep-pyro/tinynurbs/tree/master/dependencies)). But since there is no .gitmodules (as you use travis to get GLM), after using the whole repository as a submodule, the path to dependencies/glm confuses the recursive update.
There are probably a couple ways to solve this. You could change the way you handle the dependency, either to have GLM as a git submodule (with the specified version you use), or keep the travis way but without the empty directory in the repo. You could also leave the dependency handling on the users who would have to install the apt version of GLM (and I haven't encountered any issues with its latest version). Finally, the fastest "hotfix" is the separate branch suggested in this pull request.

**Comment by pradeep-pyro** [comment]
Hi @rybectom, travis is used for CI/CD (to test if things build after changes are made in a PR for e.g.), it is not used for dependency management so that shouldn't be causing problems. I am going to try to reproduce your problem locally.

In the meantime, can you confirm if you set these flags correctly in CMake? This is the intended way to use a consume a `glm` installation with tinynurbs.

- [`TINYNURBS_USE_OWN_GLM`](https://github.com/pradeep-pyro/tinynurbs/blob/master/CMakeLists.txt#L9) must be set to `OFF`
- [`GLM_ROOT_DIR`](https://github.com/pradeep-pyro/tinynurbs/blob/master/CMakeLists.txt#L8) must be set to the path of your `glm` directory

If you set these flags and it sill doesn't work as intended, then it's a bug and I will fix it rather than removing the submodule entirely.

**Comment by rybectom** [comment]
I don't have any compilation problem with the apt-installed GLM, even with the unmodified CMake. The issue comes with the submodule loading, where I cannot modify anything - it downloads the repository as is. And fails already at the recursive submodule update.

**Comment by pradeep-pyro** [comment]
Ah it's the submodule update that's giving you problems. Let me try to reproduce this problem and get back to you.

**Comment by pradeep-pyro** [comment]
Can you try compiling from [this branch](https://github.com/pradeep-pyro/tinynurbs/tree/fix_glm_submodule) and see if the submodule works?

**Comment by rybectom** [comment]
Hi, thanks for the update, there is probably one last thing - there should be "/" instead of "\\" in the submodule path, see the [answer here](https://stackoverflow.com/questions/60303060/no-submodule-mapping-found-in-gitmodules-for-path-xx). But once I change the .gitmodules file locally, the recursive update goes fine and I suppose it will pass on our remote build server as well.

**Comment by pradeep-pyro** [comment]
Thanks, fixed and merged.

**Pull request closed without merging**
